<?php


/**
 * Clevada - Content Management System and Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://clevada.com.
 *
 * LICENSE:
 * Clevada is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2021, Chimilevschi Iosif Gabriel, https://clevada.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <contact@clevada.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */


namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use View;
use App\Models\User;
use App\Models\FormData;
use App\Models\CustomPostType;
use Auth;

class AdminMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Closure(\Illuminate\Http\Request): (\Symfony\Component\HttpFoundation\Response)  $next
     */
    public function handle(Request $request, Closure $next): Response
    {

        if (Auth::user()) {
            if (Auth::user()->role == 'admin' || Auth::user()->role == 'internal') {

                // Update last activity
                User::where('id', Auth::user()->id)->update(['last_activity_at' => now()]);

                // count unread forms messages 
                //$count_unread_forms_messages = FormData::whereNull('read_at')->whereNull('deleted_at')->count();
                //View::share('count_unread_forms_messages', $count_unread_forms_messages);

                // get posts types (posts, pages and custom types)
                $custom_posts_types = CustomPostType::where('active', 1)->orderByDesc('protected')->orderBy('name')->get();
                View::share('custom_posts_types', $custom_posts_types);
            }
        }

        return $next($request);
    }
}
