<?php

/**
 * Clevada - Content Management System and Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://clevada.com.
 *
 * LICENSE:
 * Clevada is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2021, Chimilevschi Iosif Gabriel, https://clevada.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <contact@clevada.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

return [

    /*
    |--------------------------------------------------------------------------
    | Content blocks
    |--------------------------------------------------------------------------
    |
    */
    'blocks' => [
        'text' => [
            'label' => 'Simple text',
            'icon' => '<i class="bi bi-file-text"></i>'
        ],
        'editor' => [
            'label' => 'Text Editor / HTML',
            'icon' => '<i class="bi bi-textarea-t"></i>'
        ],
        'image' => [
            'label' => 'Image / Banner',
            'icon' => '<i class="bi bi-image"></i>'
        ],
        'gallery' => [
            'label' => 'Images gallery',
            'icon' => '<i class="bi bi-images"></i>'
        ],
        'video' => [
            'label' => 'Video',
            'icon' => '<i class="bi bi-play-btn"></i>'
        ],
        /*
        'card' => [
            'label' => 'Cards',
            'icon' => '<i class="bi bi-file-richtext"></i>'
        ],
        'hero' => [
            'label' => 'Hero',
            'icon' => '<i class="bi bi-card-heading"></i>'
        ],
        
        'links' => [
            'label' => 'Links',
            'icon' => '<i class="bi bi-list-ul"></i>'
        ],        
        'slider' => [
            'label' => 'Slider',
            'icon' => '<i class="bi bi-collection"></i>'
        ],       
        'custom' => [
            'label' => 'Custom',
            'icon' => '<i class="bi bi-code"></i>'
        ],
        */
        'accordion' => [
            'label' => 'Accordion',
            'icon' => '<i class="bi bi-menu-up"></i>'
        ],
        'alert' => [
            'label' => 'Alert',
            'icon' => '<i class="bi bi-exclamation-square"></i>'
        ],
        'map' => [
            'label' => 'Google Map',
            'icon' => '<i class="bi bi-geo-alt"></i>'
        ],
        'blockquote' => [
            'label' => 'Blockquote',
            'icon' => '<i class="bi bi-chat-left-quote"></i>'
        ],
        /*
        'download' => [
            'label' => 'Download',
            'icon' => '<i class="bi bi-download"></i>'
        ],        
        'form' => [
            'label' => 'Form',
            'icon' => '<i class="bi bi-input-cursor-text"></i>'
        ],
        */
        'testimonial' => [
            'label' => 'Testimonial',
            'icon' => '<i class="bi bi-star-half"></i>'
        ],
        'ad' => [
            'label' => 'Ad',
            'icon' => '<i class="bi bi-badge-ad"></i>'
        ],
        'poll' => [
            'label' => 'Poll',
            'icon' => '<i class="bi bi-pie-chart"></i>'
        ],
        /*
        'search' => [
            'label' => 'Search form',
            'icon' => '<i class="bi bi-search"></i>'
        ],
        'posts' => [
            'label' => 'Posts',
            'icon' => '<i class="bi bi-card-checklist"></i>'
        ],
        'posts_categ' => [
            'label' => 'Posts categories',
            'icon' => '<i class="bi bi-diagram-3"></i>'
        ],
        'posts_tags' => [
            'label' => 'Posts tags',
            'icon' => '<i class="bi bi-tags"></i>'
        ],
        */
    ],


    /*
    |--------------------------------------------------------------------------
    | Content blocks for footer
    |--------------------------------------------------------------------------
    |
    */
    'footer_blocks' => [
        'text' => [
            'label' => 'Simple text',
            'icon' => '<i class="bi bi-file-text"></i>'
        ],
        'editor' => [
            'label' => 'Text Editor / HTML',
            'icon' => '<i class="bi bi-textarea-t"></i>'
        ],
        'image' => [
            'label' => 'Image / Banner',
            'icon' => '<i class="bi bi-image"></i>'
        ],
        'links' => [
            'label' => 'Links',
            'icon' => '<i class="bi bi-list-ul"></i>'
        ],
        'custom' => [
            'label' => 'Custom',
            'icon' => '<i class="bi bi-code"></i>'
        ],
    ],

];
