<?php

/**
 * Clevada - Content Management System and Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://clevada.com.
 *
 * LICENSE:
 * Clevada is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2021, Chimilevschi Iosif Gabriel, https://clevada.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <contact@clevada.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\Admin;

use App\Models\Post;
use App\Models\CustomPostType;
use App\Models\Taxonomy;

use App\Models\Upload;
use App\Models\SysConfig;
use App\Models\Block;
use App\Models\PostComment;
use App\Models\PostLike;
use App\Models\Tools;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Auth;

class PostController extends Controller
{

    public function __construct(Request $request)
    {
        $this->post_type = $request->post_type ?? 'post';

        $this->taxonomies = Taxonomy::with('items')->where(['post_type' => $this->post_type, 'active' => 1, 'admin_filter' => 1])->orderBy('position')->get();

        $this->custom_post_type = CustomPostType::where(['type' => $this->post_type, 'active' => 1])->first();

        //$this->tags = PostCateg::whereNull('parent_id')->with('childCategories')->orderBy('title')->get();
    }


    /**
     * Display all posts
     */
    public function index(Request $request)
    {
        // check if user can view items
        if ($request->user()->cannot('view', Post::class)) return redirect(route('admin'))->withErrors('Forbidden');

        $search_terms = $request->search_terms;
        $search_status = $request->search_status;
        $search_categ_id = $request->search_categ_id;
        $search_tag_id = $request->search_tag_id;
        $search_featured = $request->search_featured;

        $posts = Post::with('author')->whereNull('deleted_at');

        // check if user can view own items only
        if (!$request->user()->can('viewAny', Post::class)) $posts = $posts->where('user_id', $request->user()->id);

        if ($search_status)
            $posts = $posts->where('posts.status', 'like', $search_status);

        if ($search_terms)
            $posts = $posts->where(function ($query) use ($search_terms) {
                $query->where('posts.title', 'like', "%$search_terms%")
                    ->orWhere('posts.search_terms', 'like', "%$search_terms%");
            });

        if ($search_categ_id) {
            $categ = PostCateg::find($search_categ_id);
            $categ_tree_ids = $categ->tree_ids ?? null;
            if ($categ_tree_ids)
                $categ_tree_ids_array = explode(',', $categ_tree_ids);
            else
                $categ_tree_ids_array = array();
            $posts = $posts->whereIn('posts.categ_id', $categ_tree_ids_array);
        }

        if ($search_featured == 1)
            $posts = $posts->where('posts.featured', 1);

        $posts = $posts->orderByDesc('id')->paginate(20);

        return view('admin.index', [
            'view_file' => 'posts.index',
            'active_menu' => $this->post_type ?? null,
            'menu_section' => 'posts',
            'search_terms' => $search_terms,
            'search_status' => $search_status,
            'search_featured' => $search_featured,
            'search_categ_id' => $search_categ_id,
            'search_tag_id' => $search_tag_id,
            'posts' => $posts,
            'post_type' => $this->post_type ?? null, // String
            'custom_post_type' => $this->custom_post_type ?? null, // Object  
            'taxonomies' => $this->taxonomies ?? null, // Object
        ]);
    }


    /**
     * Show page to add new resource
     */
    public function create(Request $request)
    {
        if ($request->user()->cannot('create', Post::class)) return redirect(route('admin.posts.index'))->withErrors('Forbidden');

        if ($this->post_type != 'post') {
            if ((CustomPostType::where('type', $this->custom_post_type))->doesntExist()) return redirect(route('admin.posts.index'))->withErrors('Forbidden');
        }

        /*
        $categories = PostCateg::with('childCategories')->whereNull('parent_id')
            ->orderByDesc('posts_categ.active')
            ->orderBy('posts_categ.position')
            ->orderBy('posts_categ.title')
            ->get();

        if (count($categories) == 0)
            return redirect(route('admin.posts.categ'))->with('error', 'create_post_no_categ');

        $all_tags_array = PostTag::withcount('data')->orderBy('tag')->pluck('tag')->toArray();
        if (count($all_tags_array) > 0) $all_tags = sprintf("'%s'", implode("','", $all_tags_array));
        */

        return view('admin.index', [
            'view_file' => 'posts.create',
            'active_menu' => $this->post_type ?? null,
            'post_type' => $this->post_type ?? null, // String
            'custom_post_type' => $this->custom_post_type ?? null, // Object  
            'taxonomies' => $this->taxonomies ?? null, // Object
        ]);
    }


    /**
     * Create new resource
     */
    public function store(Request $request)
    {
        if ($request->user()->cannot('create', Post::class)) return redirect(route('admin.posts.index'))->withErrors('Forbidden');

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        if ($this->post_type != 'post') {
            if ((CustomPostType::where('type', $this->custom_post_type))->doesntExist()) return redirect(route('admin.posts.index'))->withErrors('Forbidden');
        }

        $validator = Validator::make($request->all(), [
            'title' => 'required',
        ]);

        if ($validator->fails()) return redirect(route('admin.posts.create'))->withErrors($validator)->withInput();

        if ($request->slug)
            $slug = Str::slug($request->slug, '-');
        else
            $slug = Str::slug($request->title, '-');

        // check if there is another post with this slug 
        if (Post::where('slug', $slug)->exists()) {
            // if exists, add post ID in slug
            $latestID = Post::latest('id')->value('id');
            $slug = $slug . '-' . ($latestID + 1);
        }

        $post = Post::create([
            'type' => $this->post_type,
            'title' => $request->title,
            'slug' => $slug,
            'user_id' => Auth::user()->id,
            'summary' => $request->summary,
            'tags' => $request->tags,
            'status' => 'draft',
            'search_terms' => $request->search_terms,
            'meta_title' => $request->meta_title,
            'meta_description' => $request->meta_description,
            'disable_comments' => $request->has('disable_comments') ? 1 : 0,
            'disable_likes' => $request->has('disable_likes') ? 1 : 0,
            'featured' => $request->has('featured') ? 1 : 0,
        ]);

        // process image        
        if ($request->hasFile('image')) {
            $validator = Validator::make($request->all(), ['image' => 'file|image|max:5120']); // image mime, max 5 MB
            if (!$validator->fails()) {
                $image = Upload::storeImage($request->file('image'), $oldImageCode = null, $data = array('module' => 'posts', 'item_id' => $post->id));
                if ($image) Post::where('id', $post->id)->update(['image' => $image->code]);
            } else $upload_fails = true;
        }

        //PostCateg::recount_categ_items($request->categ_id);
        //Tools::generateSitemap();

        return redirect(route('admin.posts.content', ['id' => $post->id]))->with('success', 'post_created')->with('upload_fails', $upload_fails ?? null);
    }


    /**
     * Show form to edit resource     
     */
    public function show(Request $request)
    {
        $post = Post::with('author')->where('id', $request->id);

        // check if user can view own posts only
        if (!$request->user()->can('viewAny', Post::class)) $post = $post->where('user_id', $request->user()->id);

        $post = $post->first();

        if (!$post) return redirect(route('admin.posts.index'));

        if ($request->user()->cannot('view', $post)) return redirect(route('admin.posts.index'))->withErrors('Forbidden');

        $author_count_published_posts = Post::where('user_id', $post->user_id)->where('status', 'active')->count();
        $author_count_pending_posts = Post::where('user_id', $post->user_id)->where('status', 'pending')->count();

        //$all_tags_array = PostTag::orderBy('tag')->pluck('tag')->toArray();
        //if (count($all_tags_array) > 0) $all_tags = sprintf("'%s'", implode("','", $all_tags_array));

        return view('admin.index', [
            'view_file' => 'posts.update',
            'active_menu' => $this->post_type ?? null,
            'post_menu' => 'details',
            'post' => $post,
            'tags' => $tags_array ?? null,
            //'all_tags' => $all_tags ?? null,
            'author_count_published_posts' => $author_count_published_posts,
            'author_count_pending_posts' => $author_count_pending_posts,

            'post_type' => $this->post_type ?? null, // String
            'custom_post_type' => $this->custom_post_type ?? null, // Object  
            'taxonomies' => $this->taxonomies ?? null, // Object
        ]);
    }


    /**
     * Update the specified resource     
     */
    public function update(Request $request)
    {
        $post = Post::find($request->id);
        if (!$post) return redirect(route('admin.posts'));

        if ($request->user()->cannot('update', $post)) return redirect(route('admin.posts.index'))->withErrors('Forbidden');

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'categ_id' => 'required',
        ]);

        if ($validator->fails()) return redirect(route('admin.posts.show', ['id' => $request->id]))->withErrors($validator)->withInput();

        $categ = PostCateg::find($post->categ_id);

        if ($request->slug) $slug = Str::slug($request->slug, '-');
        else $slug = Str::slug($request->title, '-');

        // check if there is another post with this slug
        if (Post::where('slug', $slug)->where('id', '!=', $request->id)->exists()) {
            $slug = $slug . '-' . $request->id;
        }

        if ($request->tags) {
            // Json tags to comma separated string
            $tags_string = PostTag::jsonTagsToString($request->tags);
            $tags_array = explode(',', $tags_string);
            // check if an existing tag as deleted from tags input
            $db_post_tags = PostTagItem::where('post_id', $request->id)->get();
            foreach ($db_post_tags as $db_post_tag) {
                $db_post_tag_name = PostTag::where('id', $db_post_tag->tag_id)->value('tag');
                if (!in_array($db_post_tag_name, $tags_array)) PostTagItem::where('tag_id', $db_post_tag->tag_id)->where('post_id', $request->id)->delete();
            }
        } else PostTagItem::where('post_id', $request->id)->delete();

        Post::where('id', $request->id)->update([
            'title' => $request->title,
            'categ_id' => $request->categ_id,
            'slug' => $slug,
            'summary' => $request->summary,
            'tags' => $tags_string ?? null,
            'status' => $request->status,
            'search_terms' => $request->search_terms,
            'meta_title' => $request->meta_title,
            'meta_description' => $request->meta_description,
            'disable_comments' => $request->has('disable_comments') ? 1 : 0,
            'disable_likes' => $request->has('disable_likes') ? 1 : 0,
            'featured' => $request->has('featured') ? 1 : 0,
            'minutes_to_read' => Post::estimated_reading_time($request->id),
            'updated_by_user_id' => Auth::user()->id,
        ]);

        // process tags        
        if ($request->tags and $request->status == 'published') {
            foreach ($tags_array as $tag) {
                PostTag::storeTag($tag, $post->id);
            }
        }

        PostTagItem::recountTagItems();

        // process image        
        if ($request->hasFile('image')) {
            $validator = Validator::make($request->all(), ['image' => 'file|image|max:5120']); // image mime, max 5 MB
            if (!$validator->fails()) {
                $image = Upload::storeImage($request->file('image'), $oldImageCode = $post->image, $data = array('module' => 'posts', 'item_id' => $request->id));
                if ($image) Post::where('id', $request->id)->update(['image' => $image->code]);
            } else $upload_fails = true;
        }

        PostCateg::recount_categ_items($request->categ_id);
        Tools::generateSitemap();

        return redirect(route('admin.posts.show', ['id' => $request->id]))->with('success', 'updated')->with('upload_fails', $upload_fails ?? null);
    }


    /**
     * Remove the specified resource
     */
    public function destroy(Request $request)
    {
        $post = Post::find($request->id);
        if (!$post) return redirect(route('admin.posts.index'));

        if ($request->user()->cannot('delete', $post)) return redirect(route('admin.posts.index'))->withErrors('Forbidden');

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        Post::where('id', $request->id)->update(['deleted_at' => now()]); // move to recycle bin

        Tools::generateSitemap();

        return redirect(route('admin.posts.index'))->with('success', 'deleted');
    }


    /**
     * Remove post main image
     */
    public function delete_main_image(Request $request)
    {
        $post = Post::find($request->id);
        if (!$post) return redirect(route('admin.posts.index'));

        if ($request->user()->cannot('update', $post)) return redirect(route('admin.posts.index'))->withErrors('Forbidden');

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        if ($post->image) delete_image($post->image);

        Post::where('id', $request->id)->update(['image' => null]);

        return redirect(route('admin.posts.show', ['id' => $request->id]))->with('success', 'main_image_deleted');
    }


    /**
     * Show form to add content
     */
    public function content(Request $request)
    {
        $post = Post::with('author')->find($request->id);
        if (!$post) return redirect(route('admin.posts.index'));

        if ($request->user()->cannot('view', $post)) return redirect(route('admin.posts.index'))->withErrors('Forbidden');

        return view('admin.index', [
            'view_file' => 'posts.content',
            'active_menu' => $this->post_type ?? null,
            'menu_section' => 'posts',
            'post_menu' => 'content',
            'post' => $post,
            'post_type' => $this->post_type ?? null, // String
        ]);
    }


    /**
     * Update post content   
     */
    public function update_content(Request $request)
    {
        $post = Post::find($request->id);
        if (!$post) return redirect(route('admin.posts.index'));

        if ($request->user()->cannot('update', $post)) return redirect(route('admin.posts.index'))->withErrors('Forbidden');

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        $last_pos = Block::where('module', 'posts')->where('content_id', $request->id)->orderByDesc('position')->value('position');
        $position = ($last_pos ?? 0) + 1;

        $block = Block::create([
            'type' => $request->type,
            'module' => 'posts',
            'position' => $position,
            'content_id' => $post->id,
            'created_by_user_id' => Auth::user()->id
        ]);

        Block::regenerate_content_blocks('posts', $request->id);

        Post::where('id', $request->id)->update(['minutes_to_read' => Post::estimated_reading_time($request->id)]);

        return redirect(route('admin.blocks.show', ['id' => $block->id]));
    }



    /**
     * Remove the specified block content
     */
    public function delete_content(Request $request)
    {
        $post = Post::find($request->id);
        if (!$post) return redirect(route('admin.posts.index'));

        if ($request->user()->cannot('update', $post)) return redirect(route('admin.posts.index'))->withErrors('Forbidden');

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        Block::regenerate_content_blocks('posts', $request->id);

        Block::where('id', $request->block_id)->delete();

        Post::where('id', $request->id)->update(['minutes_to_read' => Post::estimated_reading_time($request->id)]);

        return redirect(route('admin.posts.content', ['id' => $request->id]))->with('success', 'deleted');
    }


    /**
     * Ajax sortable
     */
    public function sortable(Request $request)
    {
        if ($request->user()->cannot('update', Post::class)) return;

        $i = 0;
        $content_id = $request->id;
        $records = $request->all();

        foreach ($records['item'] as $key => $value) {

            Block::where('module', 'posts')
                ->where('content_id', $content_id)
                ->where('id', $value)
                ->update([
                    'position' => $i,
                ]);

            $i++;
        }

        Block::regenerate_content_blocks('posts', $content_id);
    }


    /**
     * Config
     */
    public function config()
    {
        if (!(Auth::user()->role == 'admin')) return redirect(route('admin'));

        return view('admin.index', [
            'view_file' => 'posts.config',
            'active_menu' => $this->post_type ?? null,
            'menu_section' => 'config',
        ]);
    }


    /**
     * Update the specified resource     
     */
    public function update_config(Request $request)
    {
        if (!(Auth::user()->role == 'admin')) return redirect(route('admin'));

        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        $inputs = $request->except('_token');

        SysConfig::update_config($inputs);

        //SysConfig::update_config('posts_per_page', $request->posts_per_page);
        //SysConfig::update_config('posts_comments_antispam_enabled', $request->posts_comments_antispam_enabled);
        //SysConfig::update_config('posts_likes_enabled', $request->posts_likes_enabled);
        //SysConfig::update_config('posts_comments_enabled', $request->posts_comments_enabled);
        //SysConfig::update_config('posts_comments_fb_enabled', $request->posts_comments_fb_enabled);

        return redirect($request->Url())->with('success', 'updated');
    }


    /**
     * All likes
     */
    public function likes(Request $request)
    {

        $likes = PostLike::with('post');
        if ($request->search_post_id) {
            $likes = $likes->where('post_id', $request->search_post_id);
            $post = Post::find($request->search_post_id);
            if (!$post) return redirect(route('admin.posts.index'));
        }
        $likes = $likes->orderByDesc('id')->paginate(25);

        return view('admin.index', [
            'view_file' => 'posts.likes',
            'active_menu' => 'interaction',
            'active_submenu' => 'likes',
            'menu_section' => 'likes',
            'search_post_id' => $request->search_post_id,
            'likes' => $likes,
            'post' => $post ?? null,
        ]);
    }


    /**
     * Delete resource
     */
    public function destroy_like(Request $request)
    {
        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        $like_post_id = PostLike::where('id', $request->id)->value('post_id');

        PostLike::where('id', $request->id)->delete();

        Post::recount_post_likes($like_post_id);

        return redirect(route('admin.posts.likes', ['search_post_id' => $request->post_id]))->with('success', 'deleted');
    }


    /**
     * All comments
     */
    public function comments(Request $request)
    {

        $search_post_id = $request->search_post_id;
        $search_status = $request->search_status;
        $search_terms = $request->search_terms;

        $comments = PostComment::with('post', 'author');

        /*
        $comments = DB::table('post_comments')
            ->leftJoin('posts', 'post_comments.post_id', '=', 'posts.id')
            ->leftJoin('users', 'post_comments.user_id', '=', 'users.id')
            ->select(
                'post_comments.*',
                'posts.title as post_title',
                'posts.slug as post_slug',
                'posts.image as post_image',
                'users.name as author_name',
                'users.email as author_email',
                'users.avatar as author_avatar',
                'users.slug as author_slug',
                DB::raw('(SELECT name FROM users WHERE post_comments.updated_by_user_id = users.id) as updated_by_user_name'),
                DB::raw('(SELECT COUNT(id) FROM post_comments WHERE ip = post_comments.ip) as ip_count_comments')
            );
        */

        if ($search_post_id) {
            $comments = $comments->where('post_id', $search_post_id);
            $post = Post::find($search_post_id);
            if (!$post) return redirect(route('admin.posts.index'));
        }

        if ($search_status)
            $comments = $comments->where('status', 'like', $search_status);

        if ($search_terms)
            $comments = $comments->where(function ($query) use ($search_terms) {
                $query->where('comment', 'like', "%$search_terms%");
            });

        $comments = $comments->orderByDesc('id')->paginate(25);

        $count_pending_comments = PostComment::where('status', 'pending')->count();

        return view('admin.index', [
            'view_file' => 'posts.comments',
            'active_menu' => 'interaction',
            'active_submenu' => 'comments',
            'menu_section' => 'comments',
            'search_post_id' => $search_post_id,
            'search_status' => $search_status,
            'search_terms' => $search_terms,
            'comments' => $comments,
            'count_pending_comments' => $count_pending_comments,
            'post' => $post ?? null,
        ]);
    }


    public function update_comment(Request $request)
    {
        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        PostComment::where('id', $request->id)
            ->update([
                'comment' => $request->comment,
                'status' => $request->status,
                'updated_by_user_id' => Auth::user()->id ?? null,
            ]);

        return redirect(route('admin.posts.comments', ['search_post_id' => $request->post_id]))->with('success', 'updated');
    }



    /**
     * Delete resource
     */
    public function delete_comment(Request $request)
    {
        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        $comment_post_id = PostComment::where('id', $request->id)->value('post_id');

        PostComment::where('id', $request->id)->delete();

        Post::recount_post_comments($comment_post_id);

        return redirect(route('admin.posts.comments', ['search_post_id' => $request->post_id]))->with('success', 'deleted');
    }
}
